app:
  default_locale: <%= ENV['DEFAULT_LOCALE'] || 'en' %>
  time_zone: 'St. Petersburg'

  secret_key_base: 'a000000000000000000000000000000000000000000000000001'
  secret_token:    'a000000000000000000000000000000000000000000000000002'

redis:
  port: 6010
  url:  "redis://localhost:6010/1"

sidekiq:
  namespace: 'example.com'
  ui:
    user: admin
    password: qwerty

action_cable:
  adapter_params:
    # adapter: async
    adapter: redis
    url: redis://localhost:6010/1
    channel_prefix: rails5app

  worker_pool_size: 4
  mount_path: 'ws://localhost:3000/app-cable'
  disable_request_forgery_protection: false
  allowed_request_origins: http://localhost:3000
